spring.application.name=backend
server.port=8888
server.error.include-message=always
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=
spring.jpa.hibernate.ddl-auto=create-drop